include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
    unnecessary_this: ignore
    use_build_context_synchronously: ignore
