name: klemat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  confetti: ^0.8.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  html: ^0.15.5+1
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/words/5_letters/5_letter_words_all.json
    - assets/words/5_letters/5_letter_answers.json
    - assets/words/5_letters/5_letter_levels.json

    - assets/words/4_letters/4_letter_words_all.json
    - assets/words/4_letters/4_letter_answers.json
    - assets/words/4_letters/4_letter_levels.json

    - assets/words/3_letters/3_letter_words_all.json
    - assets/words/3_letters/3_letter_answers.json
    - assets/words/3_letters/3_letter_levels.json

    - assets/lang/en.json
    - assets/lang/ar.json

    - assets/images/Mountains.png
    - assets/images/green_flag.png
    - assets/images/finished_flag.png
    - assets/images/locked_flag.png
    - assets/images/arab1-removebg-preview.png
    - assets/images/arab2-removebg-preview.png
    - assets/images/arab3-removebg-preview.png
    - assets/images/white_background.png
    - assets/images/dark_background.png


